export const mockUsers = [
  {
    id: "1",
    name: "Alex Johnson",
    email: "alex.johnson@example.com",
    role: "super_admin",
    status: "active",
    storageUsed: 245,
    createdAt: new Date("2024-01-15").toISOString(),
    lastActive: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "2",
    name: "Sarah Chen",
    email: "sarah.chen@example.com",
    role: "admin",
    status: "active",
    storageUsed: 512,
    createdAt: new Date("2024-02-10").toISOString(),
    lastActive: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "3",
    name: "Marcus Rodriguez",
    email: "marcus.rodriguez@example.com",
    role: "viewer",
    status: "active",
    storageUsed: 128,
    createdAt: new Date("2024-03-01").toISOString(),
    lastActive: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "4",
    name: "Emma Wilson",
    email: "emma.wilson@example.com",
    role: "admin",
    status: "offline",
    storageUsed: 356,
    createdAt: new Date("2024-01-20").toISOString(),
    lastActive: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "5",
    name: "James Park",
    email: "james.park@example.com",
    role: "viewer",
    status: "active",
    storageUsed: 87,
    createdAt: new Date("2024-03-10").toISOString(),
    lastActive: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: "6",
    name: "Lisa Anderson",
    email: "lisa.anderson@example.com",
    role: "super_admin",
    status: "offline",
    storageUsed: 178,
    createdAt: new Date("2024-02-05").toISOString(),
    lastActive: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "7",
    name: "David Kumar",
    email: "david.kumar@example.com",
    role: "viewer",
    status: "active",
    storageUsed: 234,
    createdAt: new Date("2024-03-05").toISOString(),
    lastActive: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: "8",
    name: "Rachel Turner",
    email: "rachel.turner@example.com",
    role: "admin",
    status: "active",
    storageUsed: 445,
    createdAt: new Date("2024-01-25").toISOString(),
    lastActive: new Date(Date.now() - 2700000).toISOString(),
  },
]

export const mockNotifications = [
  {
    id: "n1",
    title: "New user registration",
    message: "James Park joined the platform",
    type: "info",
    read: false,
    timestamp: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: "n2",
    title: "Storage limit warning",
    message: "Sarah Chen is at 90% storage capacity",
    type: "warning",
    read: false,
    timestamp: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "n3",
    title: "System maintenance",
    message: "Scheduled maintenance completed successfully",
    type: "success",
    read: true,
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
]

export const mockAnalytics = {
  totalUsers: 1247,
  activeUsers: 892,
  deletedUsers: 24,
  totalStorage: 1024,
  usedStorage: 723,
  userGrowth: [850, 920, 980, 1050, 1120, 1180, 1247],
  activeSessions: [720, 780, 820, 850, 870, 880, 892],
}
